# The quantale
#
#   (2ⁿ, ∪, +)
#
# generated by a group G = (n, +).
#
#   - elements are subsets
#   - addition is union
#   - multiplication is Minkowski summation
#
abstract type MinkowskiQuantale <: AbstractSemiring end

function sid(s::MinkowskiQuantale, a::T, ::Val{:R}) where {T <: Unsigned}
    return a ⊻ szero(s, T, Val(:C))
end

function sid(s::MinkowskiQuantale, a::Vec{W, T}, ::Val{:R}) where {W, T}
    return a ⊻ Vec{W, T}(szero(s, T, Val(:C)))
end

function sid(s::MinkowskiQuantale, a, ::Val{:C})
    return sid(s, sid(s, a, Val(:T)), Val(:R))
end

function szero(s::MinkowskiQuantale, ::Type{T}, ::Val{:C}) where {T <: Unsigned}
    return typemax(T)
end

function szero(s::MinkowskiQuantale, ::Type{T}, ::Val{:N}) where {T <: Unsigned}
    return zero(T)
end

function sone(s::MinkowskiQuantale, ::Type{T}, ::Val{:N}) where {T <: Unsigned}
    return one(T)
end

function splus(s::MinkowskiQuantale, a, b, ::Val{:N})
    return a | b
end

function splus(s::MinkowskiQuantale, a, b, ::Val{:C})
    return a & b
end

function sprod(s::MinkowskiQuantale, a::Vec{W, T}, b::T, ::Val{:N}, ::Val{:N}) where {W, T <: Unsigned}
    return gprod(s, gtabs(s, a)..., b)
end

function sprod(s::MinkowskiQuantale, a::T, b::Vec{W, T}, ::Val{:N}, ::Val{:N}) where {W, T <: Unsigned}
    if iscommutative(s)
        c = sprod(s, b, a, Val(:N), Val(:N))
    else
        c = sid(s, sprod(s, sid(s, b, Val(:T)), sid(s, a, Val(:T)), Val(:N), Val(:N)), Val(:T))
    end

    return c
end

function sprod(s::MinkowskiQuantale, a::Vec{W, T}, b::Vec{W, T}, tA::Val{:N}, tB::Val{:N}) where {W, T <: Unsigned}
    return Vec{W, T}(ntuple(l -> sprod(s, a[l], b[l], tA, tB), Val(W)))
end

function sprod(s::MinkowskiQuantale, a, b, ::Val{:C}, ::Val{:N})
    return sid(s, sprod(s, sid(s, a, Val(:T)), sid(s, b, Val(:R)), Val(:N), Val(:N)), Val(:R))
end

function sprod(s::MinkowskiQuantale, a, b, ::Val{:N}, ::Val{:C})
    return sid(s, sprod(s, sid(s, a, Val(:R)), sid(s, b, Val(:T)), Val(:N), Val(:N)), Val(:R))
end

@inline function smuladd(s::MinkowskiQuantale, a, b, c, tA::N_OR_T, tB::N_OR_T)
    return splus(s, sprod(s, a, b, tA, tB), c, Val(:N))
end

@inline function smuladd(s::MinkowskiQuantale, a, b, c, tA::Val, tB::Val)
    return splus(s, sprod(s, a, b, tA, tB), c, Val(:C))
end

function isidempotent(::Type{<:MinkowskiQuantale})
    return true
end

function iscommutative(::Type{<:MinkowskiQuantale})
    return true
end

@inline function sgemx_kern!(s::MinkowskiQuantale, tA::Val, tB::Val, pC::Ptr{T}, ldC::Int, AP::AbstractVector, ip0::Int, BP::AbstractVector, kp0::Int, nj::Int, ::Val{MR}) where {T, MR}
    if tA isa N_OR_T && tB isa N_OR_T
        mA, mB = Val(:N), Val(:N)
    elseif tA isa R_OR_C
        mA, mB = Val(:T), Val(:R)
    else
        mA, mB = Val(:R), Val(:T)
    end

    w = ldC * sizeof(T)

    q1 = q2 = q3 = q4 = zero(Vec{MR, T})

    @inbounds for jp in 1:nj
        a = vload(Vec{MR, T}, AP, ip0 + (jp - 1) * MR)
        TT, UU = gtabs(s, sid(s, a, mA))
        kpj = kp0 + (jp - 1) * SGEMX_NR
        q1 |= gprod(s, TT, UU, sid(s, BP[kpj    ], mB))
        q2 |= gprod(s, TT, UU, sid(s, BP[kpj + 1], mB))
        q3 |= gprod(s, TT, UU, sid(s, BP[kpj + 2], mB))
        q4 |= gprod(s, TT, UU, sid(s, BP[kpj + 3], mB))
    end

    if tA isa N_OR_T && tB isa N_OR_T
        vstore(vload(Vec{MR, T}, pC     ) | q1, pC     )
        vstore(vload(Vec{MR, T}, pC +  w) | q2, pC +  w)
        vstore(vload(Vec{MR, T}, pC + 2w) | q3, pC + 2w)
        vstore(vload(Vec{MR, T}, pC + 3w) | q4, pC + 3w)
    else
        vstore(vload(Vec{MR, T}, pC     ) & ~q1, pC     )
        vstore(vload(Vec{MR, T}, pC +  w) & ~q2, pC +  w)
        vstore(vload(Vec{MR, T}, pC + 2w) & ~q3, pC + 2w)
        vstore(vload(Vec{MR, T}, pC + 3w) & ~q4, pC + 3w)
    end
    return
end

function gnib(b::T, k::Int) where {T <: Unsigned}
    return (((b >> (4k)) & 0xf) % Int) + 1
end

function gbyte(T, U, b::Unsigned, j::Int)
    lo = gnib(b, 2j)
    hi = gnib(b, 2j + 1)
    return @inbounds T[lo] | U[hi]
end

@inline function gtab(a, b, c, d)
    z = zero(a)

    ab = a | b
    ac = a | c
    ad = a | d
    bc = b | c
    bd = b | d
    cd = c | d

    abc = ab | c
    abd = ab | d
    acd = a | cd
    bcd = b | cd

    abcd = ab | cd

    return (z, a, b, ab, c, ac, bc, abc, d, ad, bd, abd, cd, acd, bcd, abcd)
end

@inline function gtabs(s::MinkowskiQuantale, a::Vec)
    w1, x1, y1, z1 = gbase(s, a)

    w2 = gshift(s, w1)
    x2 = gshift(s, x1)
    y2 = gshift(s, y1)
    z2 = gshift(s, z1)

    T1 = gtab(w1, x1, y1, z1)
    T2 = gtab(w2, x2, y2, z2)

    return T1, T2
end

include("cyclic.jl")
include("elementary.jl")
include("metacyclic.jl")
