# ===== tpmlqt! =====
#
# tpmlqt!(V, Tm, A, B, work)
#     [A B] ← [A B] Qᴴ for the Q generated by tplqt!; V (k × n) holds the
#     reflectors, Tm (mb × k) the block factors, A is (r × k), B is (r × n).
#     (LAPACK ?TPMLQT with side = 'R', l = 0.)
#
for (tpmlqt, elty) in (
        (:dtpmlqt_, :Float64),
        (:stpmlqt_, :Float32),
        (:ztpmlqt_, :ComplexF64),
        (:ctpmlqt_, :ComplexF32),
    )
    @eval begin
        function tpmlqt!(V::AbstractMatrix{$elty}, Tm::AbstractMatrix{$elty}, A::AbstractMatrix{$elty}, B::AbstractMatrix{$elty}, work::AbstractVector{$elty})
            require_one_based_indexing(V, Tm, A, B, work)
            chkstride1(V, Tm, A, B)
            k = size(V, 1)          # number of reflectors
            n = size(V, 2)
            r = size(A, 1)          # rows of [A B]
            mb = size(Tm, 1)
            @assert size(A, 2) == k && size(B, 1) == r && size(B, 2) == n && size(Tm, 2) >= k
            @assert 1 <= mb <= k && length(work) >= mb * r
            trans = $elty <: Real ? 'T' : 'C'
            info = Ref{BlasInt}()

            ccall((BLAS.@blasfunc($tpmlqt), BLAS.libblastrampoline), Cvoid,
                (Ref{UInt8}, Ref{UInt8}, Ref{BlasInt}, Ref{BlasInt}, Ref{BlasInt}, Ref{BlasInt}, Ref{BlasInt},
                 Ptr{$elty}, Ref{BlasInt}, Ptr{$elty}, Ref{BlasInt},
                 Ptr{$elty}, Ref{BlasInt}, Ptr{$elty}, Ref{BlasInt},
                 Ptr{$elty}, Ref{BlasInt}, Clong, Clong),
                'R', trans, r, n, k, 0, mb,
                V, max(1, stride(V, 2)), Tm, max(1, stride(Tm, 2)),
                A, max(1, stride(A, 2)), B, max(1, stride(B, 2)),
                work, info, 1, 1)

            LAPACK.chklapackerror(info[])
            return A, B
        end
    end
end
