# ===== tpmqrt! =====
#
# tpmqrt!(V, Tm, A, B, work)
#     [A; B] ← Qᴴ [A; B] for the Q generated by tpqrt!; V (m × k) holds the
#     reflectors, Tm (nb × k) the block factors, A is (k × n), B is (m × n).
#     (LAPACK ?TPMQRT with side = 'L', l = 0.)
#
for (tpmqrt, elty) in (
        (:dtpmqrt_, :Float64),
        (:stpmqrt_, :Float32),
        (:ztpmqrt_, :ComplexF64),
        (:ctpmqrt_, :ComplexF32),
    )
    @eval begin
        function tpmqrt!(V::AbstractMatrix{$elty}, Tm::AbstractMatrix{$elty}, A::AbstractMatrix{$elty}, B::AbstractMatrix{$elty}, work::AbstractVector{$elty})
            require_one_based_indexing(V, Tm, A, B, work)
            chkstride1(V, Tm, A, B)
            k = size(V, 2)          # number of reflectors
            m = size(B, 1)          # rows of the pentagonal block B
            n = size(B, 2)          # columns of [A; B]
            nb = size(Tm, 1)
            @assert size(A, 1) == k && size(A, 2) == n && size(V, 1) == m && size(Tm, 2) >= k
            @assert 1 <= nb <= k && length(work) >= nb * n
            trans = $elty <: Real ? 'T' : 'C'
            info = Ref{BlasInt}()

            ccall((BLAS.@blasfunc($tpmqrt), BLAS.libblastrampoline), Cvoid,
                (Ref{UInt8}, Ref{UInt8}, Ref{BlasInt}, Ref{BlasInt}, Ref{BlasInt}, Ref{BlasInt}, Ref{BlasInt},
                 Ptr{$elty}, Ref{BlasInt}, Ptr{$elty}, Ref{BlasInt},
                 Ptr{$elty}, Ref{BlasInt}, Ptr{$elty}, Ref{BlasInt},
                 Ptr{$elty}, Ref{BlasInt}, Clong, Clong),
                'L', trans, m, n, k, 0, nb,
                V, max(1, stride(V, 2)), Tm, max(1, stride(Tm, 2)),
                A, max(1, stride(A, 2)), B, max(1, stride(B, 2)),
                work, info, 1, 1)

            LAPACK.chklapackerror(info[])
            return A, B
        end
    end
end
